[package]
name = "fl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk-decl = { version = "0.2", features = ["json"] }
fltk = { version = "^1.4", features = ["fltk-bundled"] }
serde_json = "1.0"
toml = "0.7" # for toml
serde-lexpr = "0.1.2" # for an s-expression description
cross = "0.2.5"

