[package]
name = "fl"
version = "0.1.0"
edition = "2021"


[dependencies]
fltk = { version = "^1.4", features = [] }
serde = "1.0.163" # for a turtle description
serde_yaml = "0.9.21" # for a yaml description
log = "0.4.14" # for logging
simplelog = "0.12.1" # for logging
redis = "0.23.0" # for redis
crossbeam = "0.8.0" # for crossbeam_channel