[target.arm-unknown-linux-gnueabi]
    linker = "arm-linux-gnueabi-ld"
    rustflags = ["-C", "link-arg=-L/usr/lib/arm-linux-gnueabi/"]
[target.arm-unknown-linux-gnueabihf]
    linker = "arm-linux-gnueabihf-gcc"
    rustflags = ["-C", "link-arg=-L/usr/lib/arm-linux-gnueabihf/","-C","linker=arm-linux-gnueabihf-gcc"]

