screen:
  resolution: [1024,768]
  grid: [32,24]
mqtt:
  host: "pcthink.local"
  port: 1883
redis:
  host: "pcthink.local"
  port: 6379

widget: Frame
label: "Main Frame"
pos: [0,0]
size: [16,12]
children:
- widget: Status
  label: "USB-serial"
  pos: [0,6]
  size: [3,1]
  src_topic: "dst/ESP32-44592/sys/loopback"
  src_timeout:  3000
- widget: Button
  label: Button1
  id: inc
  pos: [1,1]
  size: [3,1]
  labelcolor: "#0000ff"
  dst_topic: "dst/shaker2/shaker/shake"
  dst_payload: "1"
- widget: HorValueSlider
  label: Slider
  pos: [6,3]
  size: [10,1]
  labelcolor: "#0000ff"
- widget: Gauge
  label: RPM
  pos: [3,5]
  size: [5,5]
  labelcolor: "#0000ff"
  src_topic: "src/cutter/motor/rpm"
  src_range: [0,10000]



label_heap-shaker1:
  suffix: " Bytes"
  prefix: "Shaker1 Heap : "
  pos: [0,0]
  size: [30,100]
  src_topic: "src/shaker1/system/heap"
button_shake:
  label: "Shake"
  pos: [3,3]
  size: [30,300]
  dst_topic: "dst/shaker2/shaker/shake"
label_shaker1-latency:
  suffix: " usec"
  prefix: "Latency : "
  pos: [6,6]
  size: [30,200]
  src_topic: "src/shaker1/system/latency"


  
