screen:
  resolution: [1024,768]
  grid: [32,24]
mqtt:
  host: "pcthink.local"
  port: 1883
redis:
  host: "pcthink.local"
  port: 6379
widgets:
  - widget: Status
    label: "USB-serial"
    pos: [6,1]
    size: [4,2]
    src_topic: "src/USB0/system/alive"
    src_timeout:  3000
  - widget: Status
    label: "ESP32-Motor"
    pos: [10,1]
    size: [4,2]
    src_topic: "dst/ESP32-44592/sys/loopback"
    src_timeout:  3000
  - widget: Status
    label: "Dead"
    pos: [14,1]
    size: [4,1]
    src_topic: "dst/UNKNWON/sys/loopback"
    src_timeout:  3000
  - widget: SubText
    pos: [14,1]
    size: [6,1]
    src_topic: "dst/ESP32-44592/sys/loopback"
    src_prefix: "up  = "
    src_suffix: " ms"
    src_timeout:  3000
    src_eval: "hms(input)"
  - widget: SubGauge
    pos: [14,2]
    size: [6,6]
    label: "Latency"
    src_topic: "dst/ESP32-44592/sys/loopback"
    src_prefix: ""
    src_suffix: " sec"
    src_timeout:  3000
    src_range: [0.,1000.]
    src_eval: "input / 1000."


  
