screen:
  resolution: [1024,768]
  grid: [32,24]
mqtt:
  host: "pcthink.local"
  port: 1883
redis:
  host: "pcthink.local"
  port: 6379
widgets:
  - widget: Status
    label: "USB-serial"
    pos: [6,1]
    size: [4,1]
    src_topic: "src/USB0/system/alive"
    src_timeout:  3000
  - widget: Status
    label: "ESP32-Motor"
    pos: [10,1]
    size: [4,1]
    src_topic: "dst/ESP32-44592/sys/loopback"
    src_timeout:  3000
  - widget: Status
    label: "Dead"
    pos: [14,1]
    size: [4,1]
    src_topic: "dst/UNKNWON/sys/loopback"
    src_timeout:  3000


  
